server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      mac: 50

spring:
  application:
    name: catalog-service-dev
  lifecycle:
    timeout-per-shutdown-phase: 15s

info:
  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
        include: health, heapdump, info, prometheus
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
    probe:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"