apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-dev
  labels:
    app: catalog-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-dev
  template:
    metadata:
      labels:
        app: catalog-service-dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"

    spec:
      containers:
        - name: catalog-service-dev
          image: catalog-service-dev
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
         #   - name: SPRING_PROFILES_ACTIVE
          #    value: testdata
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
              initialDelaySeconds: 10
              periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: 9001
                initialDelaySeconds: 5
                periodSeconds: 15
          volumeMounts:
            - name: catalog-config-volume
              mountPath: /workspace/config
      volumes:
        - name: catalog-config-volume
          configMap:
            name: catalog-config