apiVersion: v1
kind: Service
metadata:
  name: catalog-service-dev
  labels:
    app: catalog-service-dev
spec:
  type: ClusterIP
  selector:
    app: catalog-service-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
